### ISSUE TITLE
Create the non-Registered Learner Scenario

### ISSUE THREAD

**Issue by mbatuhancelik** [bounswe/bounswe2022group2#47] opened 2022-03-21 07:39 UTC
### Issue Description

As discussed [meeting 3](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%233-(17.03.2022)), one of our scenarios is about:

- Learner registers to the system.
- Learner checks the profile of the Lecturer.
- Annotates something.
- Earns a badge.

@egemenatikk, @onurkomurcu, @mbatuhancelik, and @xltvy are tasked with creating this scenario.

Work to be gathered under [the wiki page](https://github.com/bounswe/bounswe2022group2/wiki/Unregistered-Learner-Scenario,-Ai-Zheng)

### Step Details

- [x] Persona
- [x] User Story
- [x]  Goals
- [x]  Preconditions
- [x]  Scenario
- [x] Acceptance Criteria

### Deadline of the Issue

21.03.2022 Monday 23:59

### Reviewer

Bahrican Yesil

### Deadline for the Review

22.03.2022 Tuesday 10:00

**Comment by mbatuhancelik** [comment] 2022-03-21 08:04
I created #48 to work on Persona and User Story. Feel free to contribute!

**Comment by egemenatikk** [comment] 2022-03-21 08:26
I created #49  to work on Goals and Pre-conditions. Feel free to contribute!

**Comment by egemenatikk** [comment] 2022-03-21 08:44
I created a wiki page for this scenario, we can add our contributions to [this page](https://github.com/bounswe/bounswe2022group2/wiki/Unregistered-Learner-Scenario,-Ai-Zheng).

**Comment by egemenatikk** [comment] 2022-03-21 08:54
I also added the [wiki page of unregistered learner scenario](https://github.com/bounswe/bounswe2022group2/wiki/Unregistered-Learner-Scenario,-Ai-Zheng) to our general wiki page and wiki sidebar.

**Comment by egemenatikk** [comment] 2022-03-21 10:02
I have finished the detailed explanations of the sections I am responsible for. All texts are commented under the sub-issue #49  and also they are written to the [wiki page of this scenario](https://github.com/bounswe/bounswe2022group2/wiki/Unregistered-Learner-Scenario,-Ai-Zheng). You can view from both places. It is ready to review, I am open to all suggestions and review feedbacks.

**Comment by mbatuhancelik** [comment] 2022-03-21 10:36
Persona and user story are added to the wiki page under #48.
Issue is edited, wiki page link is added.
Goals are edited to comply with user story.

**Comment by onurkomurcu** [comment] 2022-03-21 18:37
I will be working on Scenario and Acceptance Criteria under this issue #51. If you have any suggestions about these topics, feel free to contribute.

**Comment by bahricanyesil** [comment] 2022-03-21 19:11
I have reviewed the persona, user story, goals and pre-conditions sections of the user scenario.

I congratulate the writers, a good scenario was created. Here's the list of the things I want to mention:

- User Story: It may be good to add one or two sentences to indicate the reasons behind using our app. What I meant is our differences from other methods and the features that promotes the use of our app for Ai.
- Pre-Conditions: Will there be a pre-condition like "Choosing the interests before navigating to the home screen"

Other than these, it seems pretty good. Thank you.

**Comment by bahricanyesil** [comment] 2022-03-21 19:16
> > * Pre-Conditions: Will there be a pre-condition like "Choosing the interests before navigating to the home screen" @egemenatikk
> 
> Yes, there should be. Thank you for reminding that to me. I am adding it right now.

You're welcome, thank you too. "Kolay gelsin!"

**Comment by mbatuhancelik** [comment] 2022-03-21 19:19
> * User Story: It may be good to add one or two sentences to indicate the reasons behind using our app. What I meant is our differences from other methods and the features that promotes the use of our app for Ai. @mbatuhancelik

#48 is reopened to handle this.
Thanks for the review!

**Comment by mbatuhancelik** [comment] 2022-03-21 19:48
> > > * User Story: It may be good to add one or two sentences to indicate the reasons behind using our app. What I meant is our differences from other methods and the features that promotes the use of our app for Ai. @mbatuhancelik
> > 
> > 
> > #48 is reopened to handle this. Thanks for the review!
> 
> Thank you @mbatuhancelik! I guess I couldn't explain well what I intended to say. I did not mean to directly write our features but tried to say that it would be better to write down the pain points of the user which encourages him/her to use our app instead of the other ones.

Tried to include the main idea of PD without stating non-decided details under #48.

**Comment by xltvy** [comment] 2022-03-21 19:51
**INFO:**
I will provide mockups for this scenario.
A separate issue is created for this purpose. You can view it in issue #54  .
Now, this issue depends on that sub-issue to be reviewed and closed.

**Comment by onurkomurcu** [comment] 2022-03-21 21:15
**Scenario and Acceptance Criteria** sections are added in [Unregistered Learner Scenario page](https://github.com/bounswe/bounswe2022group2/wiki/Unregistered-Learner-Scenario,-Ai-Zheng). These can also be seen in #51. If you think any of these sections should be updated, you can reopen issue #51.

**Comment by bahricanyesil** [comment] 2022-03-21 21:50
I reviewed the parts you did @onurkomurcu, it seems enough good. Thank you! I have two questions:
One of them is about the 6th step of the scenario:
(which is "At the first login, she have to select one or more topic that she interests."), does the user really "have to" selector is it optional?

The second one is: at the home page, she clicks the search button and types a lecturer's name. Is it the intended behavior for this user to search for a lecturer name instead of a lecture or topic name?

**Comment by onurkomurcu** [comment] 2022-03-22 13:25
> I have two questions: One of them is about the 6th step of the scenario: (which is "At the first login, she have to select one or more topic that she interests."), does the user really "have to" select or is it optional?

I am also bit confused about this step. We didn't discuss about this as far as I remember. If this was discussed in the last meeting, I can change this section accordingly. But, both option looks fine to me.

> The second one is: at the home page, she clicks the search button and types a lecturer's name. Is it the intended behavior for this user to search for a lecturer name instead of a lecture or topic name?

Yes, in the goals "_**She wants to look at lecturer profiles** and view overall learner satisfaction from those lecturers' courses and take lectures about topics she is interested in from lecturers she choose_.". She search specific learner intentionally.

Thank you for your good questions Bahrican. I'm waiting for your response.

**Comment by xltvy** [comment] 2022-03-23 18:45
**INFO:**
I have prepared the mockups that explains the unregistered learner scenario, issued in #54 and provided them in the [scenario page](https://github.com/bounswe/bounswe2022group2/wiki/Unregistered-Learner-Scenario,-Ai-Zheng) under the title of **Mockup** and I have made a bit change in User Story (not structually but contextually to better fit it with the mockups)

**Comment by bahricanyesil** [comment] 2022-03-23 20:44
Everyone did great job, I am closing the issue since there is nothing to comment for now. Thank you for all contributors.

**Closed by bahricanyesil** 2022-03-23 20:44 UTC
Labels: priority-medium, status-needreview, scenario-mockup
